version: '3.8'

volumes:
  postgres_data: 
  static:

services:
  nginx:
    image: nginx:stable-alpine
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - './nginx.conf:/etc/nginx/nginx.conf'
      - '/etc/letsencrypt:/etc/letsencrypt'
      - static:/var/www/static
    depends_on:
      - backend
      - frontend
    networks:
      - dev
      
  db:
    image: postgres:16.3
    env_file: .env
    volumes:
    - postgres_data:/var/lib/postgresql/data

  backend:
    build: ./backend
    networks:
      - dev
    env_file: .env
    command: ["gunicorn", "--bind", "0.0.0.0:8000", "config.wsgi:application"]
    volumes:
      - './nginx.conf:/etc/nginx/nginx.conf'
      - static:/var/www/backend_static
    depends_on:
      - db
      
  frontend:
    build:
      context: ./frontend
    networks:
      - dev
        